### ISSUE TITLE
there is a weird light blue background behind the site on mobile

### ISSUE THREAD

**Issue by randysim** [stuysu/epsilon#120]
it is killing my eyes

**Comment by randysim** [comment]
i think this might have something to do with the stuff i changed in the react helmet or index.html file

**Comment by TheEgghead27** [comment]
I am unable to reproduce this (Firefox, Android)

**Comment by TheEgghead27** [comment]
If anyone else is able to reproduce this ( @randysim ? ) please let us know so we can investigate
I may close this issue as `wontfix` if we cannot reproduce it

**Comment by SnowyNate** [comment]
Able to reproduce, but doesn't affect the site's visibility due to the layout of my browser. (Samsung Internet, Android)
![Screenshot_20240729_165503_Samsung Internet](https://github.com/user-attachments/assets/95df29c5-4ecc-4527-9eff-e1f76667ffb7)

**Comment by SnowyNate** [comment]
I believe this is due to the color of the primary color in ThemeProvider, which my browser uses as it's background color.

**Comment by randysim** [comment]
I notice that the blue in the background is the same color as the primary blue color we use for the site. This is probably because in
comps/context/ThemeProvider.tsx, the site decides it wants to use the primary color as the background.

This is still an issue on safari on iOS devices. I'll try and look into it, but if possible get someone with an iOS device to test the site occasionally. 

![image](https://github.com/user-attachments/assets/b4876aaa-22e4-4c2e-9deb-8fd43b93fc82)

**Comment by randysim** [comment]
fixed: this had to do with iphone overscroll behavior. just had to set overscroll-behavior to contain in the html body
