### ISSUE TITLE
announcement behavior

### ISSUE THREAD

**Issue by randysim** [stuysu/epsilon#124]
for the announcements on the catalog page, have a better behavior than the list of announcements that just push the catalog down

(maybe have a separate announcements page? or a way to load more each time?)

**Comment by SnowyNate** [comment]
I was actually hoping for the announcements to be site-wide, and shown throughout all the pages. I just have to think of a good way to display this and to dismiss it if the user wants.

**Comment by TheEgghead27** [comment]
For urgent site-wide announcements (e.g. system maintenance, updates), it may be useful to have a top-of-page banner somewhat like https://www.digitalocean.com/ (minus the links to a blog and stuff) -- I suppose that should fetch from an alternate domain (something like urgent.stuysu.org?) that will return brief plaintext along the lines of "StuyActivities will be going under maintenance from 08:00 to 17:00"

For announcements in their existing use case (advertisements) I have my reservations about extending their reach to other pages (but being able to dismiss them may help -- just a matter of implementation...)

**Comment by Rahuldeb5** [comment]
Announcements are correctly order from earliest to latest. I think we should sort them in reverse order.
