### ISSUE TITLE
Pressing enter when creating an announcement does annoying behavior

### ISSUE THREAD

**Issue by randysim** [stuysu/epsilon#129]
When pressing enter to create an announcement, instead of creating a new line, it just creates the announcement.

This was something I added because I thought it made the experience better, but in fact it does not, so please remove it.

Thanks
- Randy

**Comment by smitaparida25** [comment]
Hi Randy,

I would like to work on this issue. Could you please assign it to me or provide any additional information or guidance?

Thanks!

**Comment by TheEgghead27** [comment]
Dear @smitaparida25, we are not accepting external contributions at this time.

**Comment by smitaparida25** [comment]
Thank you for letting me know.

**Comment by TheEgghead27** [comment]
Note that it may be valuable for Ctrl-Enter to still submit the announcement (akin to other comment text editors like the one here on GitHub!)
