### ISSUE TITLE
Dark mode light mode toggle icon shifts when changing between some pages 

### ISSUE THREAD

**Issue by randysim** [stuysu/epsilon#130]
This probably means the whole navbar is changing too, looks weird

**Comment by SnowyNate** [comment]
For additional information, I've noticed this only occurs when there is a scroll bar. This may be fixed by implementing a custom scroll bar, which would add to the UI enhancements in the future.

**Comment by SnowyNate** [comment]
Found a solution. Will attempt to implement this.

**Comment by SnowyNate** [comment]
The scrollbar lacks visibility when dark mode is applied. I will try to fix this.

**Comment by SnowyNate** [comment]
Fixed by PR #133 .
