### ISSUE TITLE
Unauthenticated user can access pages without anonymous functionality

### ISSUE THREAD

**Issue by TheEgghead27** [stuysu/epsilon#138]
Although the charter page claims "log in to your StuyActivities account (You've already done that!)", it is possible (via link) to access https://epsilon.stuysu.org/create without being logged in.

No action is needed on the backend, as it already rejects anonymous charter creation attempts.

**Comment by SnowyNate** [comment]
Just encountered a bug. If the user, while signed in, attempts to directly go to the create route of the website by visiting https://epsilon.stuysu.org/create, the feature implemented by this PR will be triggered. This is because for some reason, the website's sign-in process slowed down, and it takes a bit of waiting for the site to recognize that the user is actually signed in and redirect the user to the home page. Perhaps this could be fixed through adding a delay before the useEffect hook is triggered.

**Comment by TheEgghead27** [comment]
Instead of using a static delay (which may not work depending on client performance) perhaps we instead change `UserProvider.tsx` to set a specific flag in the (not currently existent) `else` case of `getUser()` -- e.g. set the grade to `-9999` (instead of default `-1`) to indicate that the client has checked that there is no session to load, and modify the check on the create page to _also_ check the grade for `-9999` (it should re-render when the UserContext is updated, so no need to worry about hooks)

**Comment by SnowyNate** [comment]
But what is causing the delayed login? I remember the site never used to take that long to get the user signed in, and the whole process would be almost instant.

**Comment by Rahuldeb5** [comment]
I think I crashed it 😅. I was testing meetings with invalid data and it seems like it started crashing.

**Comment by TheEgghead27** [comment]
Similar notes apply to the meeting page - instead of redirects, perhaps the approach from prior StuySU sites (replace the page content with a prompt (and button) to sign in) would be clear

**Comment by TheEgghead27** [comment]
Similarly, the unauthenticated landing page button for meetings should be removed

**Comment by SnowyNate** [comment]
> Similar notes apply to the meeting page - instead of redirects, perhaps the approach from prior StuySU sites (replace the page content with a prompt (and button) to sign in) would be clear

Could you show me an example of this?

**Comment by SnowyNate** [comment]
> Similarly, the unauthenticated landing page button for meetings should be removed

Working on that now.
