### ISSUE TITLE
Reject plaintext input on the keywords menu once all 3 keywords have been filled

### ISSUE THREAD

**Issue by TheEgghead27** [stuysu/epsilon#143]
This will require a small patch to the input handler function -- refer to StuyActivities for prior examples of similar processes

**Comment by Rahuldeb5** [comment]
Could you please provide more description about this issue. Thank you.

**Comment by SnowyNate** [comment]
When creating an organization, once the user has fulfilled the max limit of 3 keywords to describe their club, disallow the user from typing anything in the field, but still allow the delete key to be used to remove keywords. If keywords are removed, the user no longer fulfills the max limit of 3 keywords so they should be allowed to type in the field again.

**Comment by SnowyNate** [comment]
Perhaps add a feature that clearly shows the user they have reached their max limit of 3 keywords if they continue to type past 3 keywords - that would be nice.

**Comment by SnowyNate** [comment]
Hm. Is there a feature that throws a clear error if the user attempts to type beyond 3 keywords? I cannot test this right now as it is completely broken on mobile.

**Comment by TheEgghead27** [comment]
My original vision for this was to be similar to StuyActivities 2.0, in that keyboard input would simply be rejected; will take a look at your current work
