### ISSUE TITLE
Club meeting times are not validated

### ISSUE THREAD

**Issue by TheEgghead27** [stuysu/epsilon#148]

**Comment by Rahuldeb5** [comment]
Could you please provide more description? Thank you.

**Comment by TheEgghead27** [comment]
Meetings can be scheduled in the past, and they can be scheduled for 0 minutes (perhaps we enforce a minimum of say 30 minutes?)

**Comment by TheEgghead27** [comment]
Sane client side checks (warning the user, defaulting to 3:35 to 5:00 instead of 3:45 to 3:45) can help, but additional work (my responsibility) is needed for server side confirmation

**Comment by randysim** [comment]
There are backend validation checks already 
see here
https://github.com/stuysu/epsilon-functions/blob/master/_shared/utils.ts

**Comment by TheEgghead27** [comment]
Server side validation has been implemented in https://github.com/stuysu/epsilon-functions/pull/1
It would be useful for the client to
0. Read the error message returned by the server, and show it in the snackbar (perhaps related to #121 ?)
1. Implement the same checks, so it can warn the user
2. Default to the conventional time of 15:35 to 17:00 (3 to 5 PM) on the meeting creation interface, instead of the 0-minute duration it is now
