### ISSUE TITLE
view button not positioned properly on approve orgs

### ISSUE THREAD

**Issue by randysim** [stuysu/epsilon#192]
When the title of the club is longer than one line, the view button gets pushed to the bottom of the card, and is formatted incorrectly.

This is on https://epsilon.stuysu.org/admin, pending orgs

**Comment by Sachinsingh2002** [comment]
i want to work on this issue, can you assign it to me.

**Comment by Rahuldeb5** [comment]
Hello @Sachinsingh2002 we are currently not accepting contributions outside of our organization. Thank you for understanding and have a good rest of your day.

**Comment by randysim** [comment]
fixed
