### ISSUE TITLE
Catalog page shows loading spinner even when there are no more clubs to display

### ISSUE THREAD

**Issue by TheEgghead27** [stuysu/epsilon#197]
This behavior is confusing to users who may be expecting more clubs to show up when there are in fact none. 

Instead, it may be helpful to display some small, gray text with something along the lines of "Total of X clubs"

**Comment by Rahuldeb5** [comment]
```
                <InfiniteScroll
                    dataLength={searchState.offset}
                    next={getOrgs}
                    hasMore={searchState.more}
                    loader={<Loading />}
                    endMessage={
                        <Box>
                            {approvedOrgs.length === 0 ? (
                                <Typography align="center" variant="h3">
                                    No Organizations Found.
                                </Typography>
                            ) : (
                                <Typography align="center" variant="h3">
                                    Total of {approvedOrgs.length}{" "}
                                    {`Organization${approvedOrgs.length > 1 ? "s" : ""}`}
                                </Typography>
                            )}
                        </Box>
                    }
                    style={{ overflow: "hidden", paddingTop: "20px" }}
                >
```

The end message is already there, but why is it not working?

**Comment by TheEgghead27** [comment]
I would investigate whether `hasMore` is being updated correctly.

**Comment by SnowyNate** [comment]
This is still an ongoing bug.

**Comment by SnowyNate** [comment]
Another problem in addition to this: Even when there ARE more clubs to display, the site does not show all of them, instead stopping after about 10 clubs and showing the infinite loading spinner.

**Comment by TheEgghead27** [comment]
We now have a solution for the time being, but a solution that does not have flickering when loading new clubs would be preferable.

**Comment by SnowyNate** [comment]
Excellent work and thank you for fixing that- that was a major issue. Could you elaborate on what you said?

**Comment by TheEgghead27** [comment]
If you scroll down now, the bug is fixed but you may see flickering as the new entries are rendered -- it would be ideal to avoid this but it is understandable if it cannot be (I forget if StuyActivities 2.0 also used the no-longer-working library)
