### ISSUE TITLE
Fix the catalog layout

### ISSUE THREAD

**Issue by Rahuldeb5** [stuysu/epsilon#253]
![Image](https://github.com/user-attachments/assets/1f0046a9-e41c-4f50-bcde-2093a92cc1e6)

Maybe set all organizations to a certain length and cut off overflow and force users to click on organization to check for more details.

**Comment by plrcgrss** [comment]
Hey, could you assign me on this issue? Would love to solve this!:)

**Comment by TheEgghead27** [comment]
Dear Paul,

I hope you are well.

As per our CONTRIBUTING.md, we are not currently accepting external contributions 
We appreciate the offer, but are currently unable to accept your help.

Thank you for your understanding.

**Comment by Rahuldeb5** [comment]
Update 12/8/2024: @k4limul s started. Just PR your branch when you're done.
