### ISSUE TITLE
Should we add recurring rooms?

### ISSUE THREAD

**Issue by randysim** [stuysu/epsilon#47]
Should we give the club the ability to book a room for the rest of the year? This seems kind of scary because once this is a feature, EVERY club will be doing it. 

Here's my thoughts:
right now, only committed clubs take the time to book all the rooms for the rest of the year because it's a long and arduous process. But if we set the standard for booking clubs to be extremely easy, then clubs that don't hold meetings consistently will just hold onto a room for that day and never let it go (low barrier of entry to do that)

**Comment by SnowyNate** [comment]
Perhaps we could make it so that club owners would have to request for the feature to be added to their club?
