### ISSUE TITLE
create documentation page and contribution guide

### ISSUE THREAD

**Issue by randysim** [stuysu/epsilon#51]
either through github or maybe it could be a page on the actual website?

probably through github is best though

**Comment by SnowyNate** [comment]
Can this be closed as completed? @randysim @TheEgghead27 @Rahuldeb5

**Comment by TheEgghead27** [comment]
I will write a few formalities in a `CONTRIBUTING.md` this weekend - there are some loose ends I've noticed that we have to tie up
