### ISSUE TITLE
Strange hover-over effect on organizations in catalog

### ISSUE THREAD

**Issue by SnowyNate** [stuysu/epsilon#6]
Upon hovering over any organization in the catalog tab, brightness/exposure of the tile increases, decreasing visibility. Minor but still a strange bug that is quite displeasing.
![image](https://github.com/stuysu/epsilon/assets/145233084/90c36ddf-9691-4703-b7c3-ccbd87c867df)

**Comment by randysim** [comment]
I see, this is caused because the way I implemented a hover effect was by creating a brightness filter in CSS. This is not ideal and should be fixed. (it was also developed in dark mode so I never tried it on white theme). Good catch

**Comment by randysim** [comment]
fixed this by using ThemeProvider to adjust hover effect (and by simply changing background color rather than adding a filter)
